version: 1.1
kind: component
name: train-model-gpu
description: Job for training a predictive model using GPU.
tags: [model_training, keras, gpu]
inputs:
  - name: WORKING_DIR
    description: The working directory for the job to run in.
    isOptional: true
    type: str
  - name: SA_CRED_PATH
    description: Path to credential file for GCP service account.
    isOptional: true
    type: str
    value: /var/secret/cloud.google.com/gcp-service-account.json
    toEnv: GOOGLE_APPLICATION_CREDENTIALS
run:
  kind: job
  connections: [fstore-pvc]
  environment:
    imagePullSecrets: ["gcp-imagepullsecrets"]
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "present"
        effect: "NoSchedule"
  volumes:
    - name: gcp-service-account
      secret:
        secretName: "gcp-sa-credentials"
  container:
    image: asia.gcr.io/{{cookiecutter.gcp_project_id}}/model-train:0.1.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args: [
      "source ~/.bashrc;",
      "python",
      "src/train_model.py"
    ]
    resources:
      requests:
        memory: "4Gi"
        cpu: "4"
      limits:
        memory: "8Gi"
        cpu: "8"
    volumeMounts:
      - name: gcp-service-account
        mountPath: /var/secret/cloud.google.com
